apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpserver-istio
spec:
  gateways:
    - httpserver-istio
  hosts:
    - istio.hj.io
  http:
    - route:
        - destination:
            host: httpserver.httpistio.svc.cluster.local
            port:
              number: 80
      fault:
        abort:
          httpStatus: 500
          precentage:
            value: 50
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpserver-istio
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - istio.hj.io
      port:
        name: httpserver
        number: 443
        protocol: HTTPS
      tls:
        credentialName: httpserver-cert
        mode: httpserver-istio
